CREATE TABLE table_products
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     TEXT           NOT NULL CHECK ( name != ''),
    type     TEXT           NOT NULL CHECK ( type != '' ),
    color    TEXT           NULL CHECK ( color != '' ),
    calories DECIMAL(10, 2) NOT NULL CHECK ( calories > 0 )
);
INSERT INTO table_products(name, type, color, calories)
VALUES ('Apple', 'Fruit', 'Red', 52.5),
       ('Banana', 'Fruit', 'Yellow', 90.1),
       ('Carrot', 'Vegetable', 'Orange', 41.0),
       ('Tomato', 'Vegetable', 'Red', 38.0)
;


SELECT * FROM table_products;
